#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG_DIR = ROOT / "config"
DATA_DIR = ROOT / "data"
USER_INPUT_DIR = ROOT / "user-input"
RESUME_EXAMPLES_DIR = USER_INPUT_DIR / "resume-examples"
TEMPLATES_DIR = ROOT / "templates" / "setup"

PROFILE_PATH = CONFIG_DIR / "profile.yml"
SIGNAL_RULES_EXAMPLE_PATH = CONFIG_DIR / "resume-signal-rules.example.yml"
SIGNAL_RULES_PATH = CONFIG_DIR / "resume-signal-rules.yml"
JOB_INTAKE_RULES_PATH = CONFIG_DIR / "job-intake-rules.yml"
DB_TEMPLATE_PATH = DATA_DIR / "job-log.template.db"
DB_PATH = DATA_DIR / "job-log.db"
CV_PATH = DATA_DIR / "cv.md"
APPLICATIONS_PATH = DATA_DIR / "applications.md"
EVALUATED_PATH = DATA_DIR / "evaluated.md"
SKILL_GAP_PATH = DATA_DIR / "skill-gap-cache.md"


PROFILE_TEMPLATE = """# Job-Logger Profile Configuration
# Generated by scripts/setup.py

candidate:
  full_name: "{full_name}"
  display_name: "{display_name}"
  email: "{email}"
  phone: "{phone}"
  location: "{location}"
  linkedin: "{linkedin}"
  github: "{github}"
  clearance_eligible: {clearance_eligible}

target_roles:
  primary:
{primary_roles}

  archetypes:
{archetype_rows}

narrative:
  headline: "{headline}"
  exit_story: >
    Add your current transition summary here.
  superpowers:
    - "Add a concise strength here"
    - "Add another concise strength here"
  proof_points:
    - name: "Replace with a key project"
      hero_metric: "Replace with the outcome or metric"
"""


def print_step(title: str, detail: str = "") -> None:
    print(f"\n[{title}]")
    if detail:
        print(detail)


def prompt_text(label: str, default: str = "", non_interactive: bool = False) -> str:
    if non_interactive:
        return default
    suffix = f" [{default}]" if default else ""
    response = input(f"{label}{suffix}: ").strip()
    return response or default


def prompt_yes_no(label: str, default: bool = True, non_interactive: bool = False) -> bool:
    if non_interactive:
        return default
    options = "Y/n" if default else "y/N"
    response = input(f"{label} [{options}]: ").strip().lower()
    if not response:
        return default
    return response in {"y", "yes"}


def sanitize_yaml(value: str) -> str:
    return str(value).replace("\\", "\\\\").replace('"', '\\"')


def as_yaml_list(items: list[str], indent: int = 4) -> str:
    prefix = " " * indent
    if not items:
        return f"{prefix}- \"generalist\""
    return "\n".join(f'{prefix}- "{sanitize_yaml(item)}"' for item in items)


def build_default_archetype_rows(selected: list[str]) -> str:
    rows = []
    ordered = []
    for key in selected or ["general"]:
        normalized = key.strip()
        if normalized and normalized not in ordered:
            ordered.append(normalized)
    for key in ordered:
        fit = "primary"
        interest = 8
        rows.append(
            f'    - name: "{key}"\n'
            f'      level: "Mid"\n'
            f'      fit: "{fit}"\n'
            f"      interest: {interest}\n"
            f'      notes: "Customize this archetype for your background."'
        )
    return "\n".join(rows)


def build_job_intake_rules(selected: list[str]) -> str:
    ordered = []
    for key in selected or ["general"]:
        normalized = key.strip()
        if normalized and normalized not in ordered:
            ordered.append(normalized)

    archetype_blocks = []
    candidate_keywords = []
    for key in ordered:
        archetype_blocks.append(
            f"  - key: \"{sanitize_yaml(key)}\"\n"
            f"    keywords:\n"
            f"      - keyword: \"{sanitize_yaml(key)}\"\n"
            f"        weight: 8"
        )
        candidate_keywords.append(key)

    if not archetype_blocks:
        archetype_blocks.append(
            '  - key: "general"\n'
            '    keywords:\n'
            '      - keyword: "software engineer"\n'
            '        weight: 4'
        )
        candidate_keywords.append("software engineer")

    candidates_text = "\n".join(f'  - "{sanitize_yaml(item)}"' for item in candidate_keywords)
    return (
        "# Job Intake Archetype Rules\n"
        "# Generated by scripts/setup.py\n\n"
        "archetypes:\n"
        f"{chr(10).join(archetype_blocks)}\n\n"
        "candidate_keywords:\n"
        f"{candidates_text}\n\n"
        "stopwords:\n"
        '  - term: "and"\n'
        "    kind: stopword\n"
        '  - term: "the"\n'
        "    kind: stopword\n"
    )


def ensure_file_from_template(path: Path, template_path: Path) -> bool:
    if path.exists():
        return False
    if not template_path.exists():
        raise FileNotFoundError(f"Missing setup template: {template_path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(template_path, path)
    return True


def ensure_db_from_template(db_path: Path, template_path: Path) -> bool:
    if db_path.exists():
        return False
    if not template_path.exists():
        raise FileNotFoundError(f"Missing DB template: {template_path}")
    db_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(template_path, db_path)
    return True


def copy_resume_examples(paths: list[str]) -> list[Path]:
    copied: list[Path] = []
    RESUME_EXAMPLES_DIR.mkdir(parents=True, exist_ok=True)
    for raw in paths:
        source = Path(raw.strip()).expanduser()
        if not raw.strip():
            continue
        if not source.exists() or not source.is_file():
            print(f"  Skipped missing file: {source}")
            continue
        target = RESUME_EXAMPLES_DIR / source.name
        shutil.copy2(source, target)
        copied.append(target)
    return copied


def parse_primary_roles_from_profile(profile_text: str) -> list[str]:
    """Extract primary role archetypes from profile.yml text."""
    match = re.search(r'primary:\s*\n((?:\s+- "[^"]+"\s*\n)+)', profile_text)
    if not match:
        return ["general"]
    items = re.findall(r'"([^"]+)"', match.group(1))
    return items if items else ["general"]


def generate_profile(non_interactive: bool) -> tuple[str, list[str]]:
    print_step(
        "Profile",
        "This step creates config/profile.yml. The setup stores enough data for the app to know who the candidate is and which role directions to favor.",
    )
    full_name = prompt_text("Full legal/display name", "Jane Smith", non_interactive)
    display_name = prompt_text("Short display name", full_name, non_interactive)
    email = prompt_text("Email", "jane@example.com", non_interactive)
    phone = prompt_text("Phone", "", non_interactive)
    location = prompt_text("Location", "Remote, United States", non_interactive)
    linkedin = prompt_text("LinkedIn URL", "", non_interactive)
    github = prompt_text("GitHub URL", "", non_interactive)
    headline = prompt_text("Short headline", "Software Engineer", non_interactive)
    clearance = prompt_yes_no("Security-clearance eligible?", False, non_interactive)

    role_focus_raw = prompt_text(
        "Primary role archetypes (comma-separated; these become your initial DB archetypes)",
        "general",
        non_interactive,
    )
    role_focus = [item.strip() for item in role_focus_raw.split(",") if item.strip()] or ["general"]

    profile_text = PROFILE_TEMPLATE.format(
        full_name=sanitize_yaml(full_name),
        display_name=sanitize_yaml(display_name),
        email=sanitize_yaml(email),
        phone=sanitize_yaml(phone),
        location=sanitize_yaml(location),
        linkedin=sanitize_yaml(linkedin),
        github=sanitize_yaml(github),
        clearance_eligible=str(clearance).lower(),
        primary_roles=as_yaml_list(role_focus, indent=4),
        archetype_rows=build_default_archetype_rows(role_focus),
        headline=sanitize_yaml(headline),
    )
    return profile_text, role_focus


def run_command(command: list[str], description: str) -> bool:
    print_step("Run", description)
    try:
        completed = subprocess.run(command, cwd=str(ROOT), check=True)
    except FileNotFoundError:
        print(f"  Command not found: {command[0]}")
        return False
    except subprocess.CalledProcessError as exc:
        print(f"  Command failed with exit code {exc.returncode}: {' '.join(command)}")
        return False
    return completed.returncode == 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Guided first-run setup for Job-Logger.")
    parser.add_argument("--non-interactive", action="store_true", help="Use defaults instead of prompting.")
    parser.add_argument("--skip-install", action="store_true", help="Skip npm install.")
    parser.add_argument("--skip-db", action="store_true", help="Skip database setup.")
    parser.add_argument("--force-profile", action="store_true", help="Overwrite config/profile.yml.")
    args = parser.parse_args()

    print("Job-Logger setup")
    print("This script sets up the app without requiring an agent.")
    print("It copies tracked starter templates, captures your role preferences, and prepares the deterministic DB/config state.")

    for directory in (CONFIG_DIR, DATA_DIR, USER_INPUT_DIR, RESUME_EXAMPLES_DIR):
        directory.mkdir(parents=True, exist_ok=True)

    created = []
    role_focus: list[str] | None = None

    if args.force_profile or not PROFILE_PATH.exists():
        profile_text, role_focus = generate_profile(args.non_interactive)
        PROFILE_PATH.write_text(profile_text, encoding="utf-8")
        created.append(PROFILE_PATH)
    if ensure_file_from_template(SIGNAL_RULES_PATH, SIGNAL_RULES_EXAMPLE_PATH):
        created.append(SIGNAL_RULES_PATH)
    if not JOB_INTAKE_RULES_PATH.exists():
        if role_focus is None and PROFILE_PATH.exists():
            role_focus = parse_primary_roles_from_profile(PROFILE_PATH.read_text(encoding="utf-8"))
        JOB_INTAKE_RULES_PATH.write_text(build_job_intake_rules(role_focus or ["general"]), encoding="utf-8")
        created.append(JOB_INTAKE_RULES_PATH)

    if ensure_file_from_template(CV_PATH, TEMPLATES_DIR / "data" / "cv.md"):
        created.append(CV_PATH)
    if ensure_file_from_template(APPLICATIONS_PATH, TEMPLATES_DIR / "data" / "applications.md"):
        created.append(APPLICATIONS_PATH)
    if ensure_file_from_template(EVALUATED_PATH, TEMPLATES_DIR / "data" / "evaluated.md"):
        created.append(EVALUATED_PATH)
    if ensure_file_from_template(SKILL_GAP_PATH, TEMPLATES_DIR / "data" / "skill-gap-cache.md"):
        created.append(SKILL_GAP_PATH)

    print_step(
        "Resume Examples",
        "If you already have resume examples or source docs, you can copy them into user-input/resume-examples for future import work.",
    )
    resume_path_raw = prompt_text(
        "Paths to resume example files (comma-separated, optional)",
        "",
        args.non_interactive,
    )
    copied = copy_resume_examples([item for item in resume_path_raw.split(",") if item.strip()])

    if created:
        print("Created starter files:")
        for path in created:
            print(f"  - {path.relative_to(ROOT)}")
    else:
        print("Starter files already existed; nothing new was created.")

    if copied:
        print("Imported resume examples:")
        for path in copied:
            print(f"  - {path.relative_to(ROOT)}")

    npm_available = shutil.which("npm") is not None
    if not args.skip_install and npm_available:
        should_install = prompt_yes_no("Run npm install now?", True, args.non_interactive)
        if should_install:
            run_command(["npm", "install"], "Installing Node dependencies")
    elif not npm_available and not args.skip_install:
        print("npm was not found. Install Node.js, then run `npm install` manually.")

    node_available = shutil.which("node") is not None
    if not args.skip_db and node_available:
        should_init_db = prompt_yes_no("Initialize the deterministic setup database now?", True, args.non_interactive)
        if should_init_db:
            if ensure_db_from_template(DB_PATH, DB_TEMPLATE_PATH):
                created.append(DB_PATH)
            db_ready = run_command(["node", "scripts/db/db-init.mjs", "setup"], "Copying template DB if needed and applying migrations")
            if db_ready:
                run_command([sys.executable, "scripts/db/sync_profile_archetypes.py"], "Syncing profile archetypes into the local DB")
                run_command([sys.executable, "scripts/db/sync_job_intake.py"], "Syncing job intake rules into the local DB")
                run_command([sys.executable, "scripts/db/sync_resume_policy.py"], "Generating generic resume display rules in the local DB")
    elif not node_available and not args.skip_db:
        print("node was not found. Install Node.js, then run `node scripts/db/db-init.mjs setup` manually.")

    print_step(
        "Next Steps",
        "Setup completed. You now have a generic install. To make resume generation truly personal, replace the starter CV/profile content with your own source material and extend the import path from those files into the DB-backed resume schema.",
    )
    print("Recommended next commands:")
    print("  - npm run setup")
    print("  - npm run db:setup")
    print("  - npm run db:sync-profile")
    print("  - npm run db:sync-intake")
    print("  - npm run db:sync-resume-policy")
    print("  - npm run sync-check")
    print("  - python log_job.py --help")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
